package jeuCodeSecret;

import java.util.Scanner;

public class Main {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String code = generateCode();
		Scanner sc = new Scanner(System.in);
		boolean playing = true;
		
		//start the game
		while(playing) {
			//get user input
			System.out.println("Inserer un numero : ");
			String codeProposal = sc.nextLine();
			//check if correct input
			if(codeProposal.matches("[0-9]{4}")) {
				//check if the player guessed the code
				if(code.equals(codeProposal)) {
					System.out.println("Bravo! vous avez deviné le code!");
					return;
				}
			}
			
			//check if any numbers are correct placed
			int correctNumbers = checkIfNumbersAreCorrectPlaced(codeProposal, code);
			if(correctNumbers>0) {
				System.out.println(" -> "+correctNumbers + " chiffre" + (correctNumbers > 1 ? "s" : "") + " bien placé" + (correctNumbers > 1 ? "s" : ""));
			}
		}
	}
	
	
	public static int checkIfNumbersAreCorrectPlaced(String codeProposal, String code) {
		/**
		 * Function to check if any number is correctly placed
		 * @param codeProposal, the code proposed by the user
		 * @param code the code generated by the system
		 * @return the amount of correct placed codes
		 */
		int nOfPresentChars = 0;
		//handle if some characters are correct and correct placed
		//go throught the loop
		for(int i=0; i<code.length() && i<codeProposal.length(); i++) {
			//check if the 2 characters from both list with same index are the same
			if(code.charAt(i) == codeProposal.charAt(i)) {
				nOfPresentChars++;
			}
		}
		return nOfPresentChars;
	}
	
	
	public static String generateCode() {
		/**
		 * function to generate the random number
		 * @return a number between 0000 and 9999 
		 */
		int num = (int) (Math.random() * 10000);
		return String.format("%04d", num);
	}

}
